name: Repository Dispatch - Read Later
on:
  repository_dispatch:
    types: [read-later]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the client payload context
        env:
          EVENT: ${{ toJson(github.event) }}
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: |
          echo "$EVENT"
          echo "$PAYLOAD_CONTEXT"

      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Extract and write article
        run: |
          echo '${{ toJson(github.event) }}' > payload.json
          python extract.py
          pwd
          ls -al

      - name: Commit and push metadata.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add metadata.json
          git commit -m "Update metadata.json [skip ci]" || echo "No changes to commit"
          git push origin main
