name: Repository Dispatch - Read Later
permissions:
  contents: write
on:
  repository_dispatch:
    types: [read-later]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the event
        env:
          EVENT: ${{ toJson(github.event) }}
        run: echo "$EVENT"

      - name: Checkout source repo
        uses: actions/checkout@v4

      #      - name: Setup Env
      #        uses: oleksiyrudenko/gha-git-credentials@v2-latest
      #        with:
      #          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Extract and convert
        run: echo '${{ toJson(github.event) }}' | ./extract

      - name: Debug
        run: |
          pwd
          ls -al
          find .
          env

      - name: Install zola
        run: sudo snap install --edge zola

      - name: Generate static site
        run: zola --root site build

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/public/

  #      - name: Commit and Push
  #        run: |
  #          git add data/* site/*
  #          git commit -m "Update content [skip ci]" || echo "No changes to commit"
  #          git push origin main

  deploy:
    needs: build

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
