name: Repository Dispatch - Read Later
permissions:
  contents: write
on:
  repository_dispatch:
    types: [read-later]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the event
        env:
          EVENT: ${{ toJson(github.event) }}
        run: echo "$EVENT"

      - name: Checkout source repo
        uses: actions/checkout@v4

      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Extract and write article
        run: |
          echo '${{ toJson(github.event) }}' > payload.json
          python extract.py

      - name: Commit and push metadata.json
        run: |
          git add data/*
          git commit -m "Update data [skip ci]" || echo "No changes to commit"
          git push origin main
